apiVersion: v1
kind: Namespace
metadata:
  name: kaniko
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kaniko
  namespace: kaniko
---
apiVersion: v1
kind: Secret
metadata:
  name: kaniko
  annotations:
    kubernetes.io/service-account.name: kaniko
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kaniko
  namespace: kaniko
rules:
- apiGroups:
  - ''
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kaniko
  namespace: kaniko
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kaniko
subjects:
- kind: ServiceAccount
  name: kaniko
---
